-- 1. Enable Required Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create Profiles table (extends Supabase Auth users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  role TEXT DEFAULT 'creator' CHECK (role IN ('supplier', 'creator', 'both')),
  avatar_url TEXT,
  website TEXT,
  bio TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Categories table with impact factors
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT UNIQUE,
  description TEXT,
  methane_reduction_factor FLOAT DEFAULT 0.0, -- Methane saved per unit weight (kg)
  co2_reduction_factor FLOAT DEFAULT 0.0,     -- CO2 saved per unit weight (kg)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Waste Listings table
CREATE TABLE listings (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  supplier_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  category_id BIGINT REFERENCES categories(id) NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  quantity FLOAT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'kg' CHECK (unit IN ('kg', 'lbs', 'grams', 'yards', 'tonnes')),
  price DECIMAL(10,2) DEFAULT 0.00,
  location TEXT,
  image_url TEXT,
  status TEXT DEFAULT 'available' CHECK (status IN ('available', 'pending', 'sold', 'archived')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create Recipes Library
CREATE TABLE recipes (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id) NOT NULL,
  creator_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  slug TEXT UNIQUE,
  description TEXT,
  instructions JSONB NOT NULL, -- Step-by-step instructions
  materials_needed JSONB NOT NULL, -- List of required materials
  difficulty_level TEXT DEFAULT 'medium' CHECK (difficulty_level IN ('easy', 'medium', 'hard')),
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Create Impact Reports
CREATE TABLE impact_reports (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  listing_id UUID REFERENCES listings(id) ON DELETE SET NULL,
  category_id BIGINT REFERENCES categories(id) NOT NULL,
  weight_diverted FLOAT NOT NULL,
  methane_saved FLOAT NOT NULL,
  co2_equivalent_saved FLOAT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Automated Updated At Function & Triggers
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_profiles BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER set_updated_at_listings BEFORE UPDATE ON listings FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER set_updated_at_recipes BEFORE UPDATE ON recipes FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

-- 8. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE impact_reports ENABLE ROW LEVEL SECURITY;

-- 9. Create RLS Policies

-- Profiles: Public read, User update
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Categories: Public read
CREATE POLICY "Categories are viewable by everyone" ON categories FOR SELECT USING (true);

-- Listings: Public read, Authenticated create, Owner update/delete
CREATE POLICY "Listings are viewable by everyone" ON listings FOR SELECT USING (status = 'available');
CREATE POLICY "Authenticated users can create listings" ON listings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Suppliers can update their own listings" ON listings FOR UPDATE USING (auth.uid() = supplier_id);
CREATE POLICY "Suppliers can delete their own listings" ON listings FOR DELETE USING (auth.uid() = supplier_id);

-- Recipes: Public read, Authenticated create
CREATE POLICY "Recipes are viewable by everyone" ON recipes FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create recipes" ON recipes FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Impact Reports: User read own reports, Authenticated create
CREATE POLICY "Users can view their own impact reports" ON impact_reports FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Authenticated users can create impact reports" ON impact_reports FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 11. Create Scans table for AI classifications
CREATE TABLE scans (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  material_name TEXT NOT NULL,
  category TEXT NOT NULL,
  suggested_use TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE scans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own scans" ON scans FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "Public can create scans" ON scans FOR INSERT WITH CHECK (true);

-- 12. Seed Data
INSERT INTO categories (name, slug, description, methane_reduction_factor, co2_reduction_factor) VALUES
('Food Waste', 'food-waste', 'Organic waste from kitchens and restaurants', 0.8, 1.2),
('Textiles', 'textiles', 'Denim scraps, textile offcuts, and fabric waste', 0.1, 0.5),
('Plastic', 'plastic', 'Industrial and post-consumer plastics', 0.05, 0.3),
('Wood Scraps', 'wood-scraps', 'Leftover wood from construction or furniture making', 0.2, 0.4),
('Coffee Grounds', 'coffee-grounds', 'Spent coffee grounds from cafes', 0.9, 1.1);
